// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lht102/workflow-playground/approval-service/ent/payment"
	"github.com/lht102/workflow-playground/approval-service/ent/review"
	"github.com/lht102/workflow-playground/approval-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	paymentFields := schema.Payment{}.Fields()
	_ = paymentFields
	// paymentDescRequestID is the schema descriptor for request_id field.
	paymentDescRequestID := paymentFields[1].Descriptor()
	// payment.DefaultRequestID holds the default value on creation for the request_id field.
	payment.DefaultRequestID = paymentDescRequestID.Default.(func() uuid.UUID)
	// paymentDescRemark is the schema descriptor for remark field.
	paymentDescRemark := paymentFields[3].Descriptor()
	// payment.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	payment.RemarkValidator = paymentDescRemark.Validators[0].(func(string) error)
	// paymentDescCreateTime is the schema descriptor for create_time field.
	paymentDescCreateTime := paymentFields[4].Descriptor()
	// payment.DefaultCreateTime holds the default value on creation for the create_time field.
	payment.DefaultCreateTime = paymentDescCreateTime.Default.(func() time.Time)
	// paymentDescUpdateTime is the schema descriptor for update_time field.
	paymentDescUpdateTime := paymentFields[5].Descriptor()
	// payment.DefaultUpdateTime holds the default value on creation for the update_time field.
	payment.DefaultUpdateTime = paymentDescUpdateTime.Default.(func() time.Time)
	// payment.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	payment.UpdateDefaultUpdateTime = paymentDescUpdateTime.UpdateDefault.(func() time.Time)
	reviewFields := schema.Review{}.Fields()
	_ = reviewFields
	// reviewDescReviewerID is the schema descriptor for reviewer_id field.
	reviewDescReviewerID := reviewFields[2].Descriptor()
	// review.ReviewerIDValidator is a validator for the "reviewer_id" field. It is called by the builders before save.
	review.ReviewerIDValidator = reviewDescReviewerID.Validators[0].(func(string) error)
	// reviewDescCreateTime is the schema descriptor for create_time field.
	reviewDescCreateTime := reviewFields[4].Descriptor()
	// review.DefaultCreateTime holds the default value on creation for the create_time field.
	review.DefaultCreateTime = reviewDescCreateTime.Default.(func() time.Time)
	// reviewDescUpdateTime is the schema descriptor for update_time field.
	reviewDescUpdateTime := reviewFields[5].Descriptor()
	// review.DefaultUpdateTime holds the default value on creation for the update_time field.
	review.DefaultUpdateTime = reviewDescUpdateTime.Default.(func() time.Time)
	// review.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	review.UpdateDefaultUpdateTime = reviewDescUpdateTime.UpdateDefault.(func() time.Time)
}
