// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	uuid "github.com/google/uuid"
)

// Defines values for PaymentStatus.
const (
	APPROVED PaymentStatus = "APPROVED"
	PENDING  PaymentStatus = "PENDING"
	REJECTED PaymentStatus = "REJECTED"
)

// Defines values for ReviewEvent.
const (
	APPROVE ReviewEvent = "APPROVE"
	REJECT  ReviewEvent = "REJECT"
)

// CreatePaymentRequest defines model for CreatePaymentRequest.
type CreatePaymentRequest struct {
	RequestId *uuid.UUID `json:"request_id,omitempty"`
}

// CreateReviewRequest defines model for CreateReviewRequest.
type CreateReviewRequest struct {
	Comment    *string     `json:"comment,omitempty"`
	Event      ReviewEvent `json:"event"`
	ReviewerId string      `json:"reviewer_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ListPaymentsResponse defines model for ListPaymentsResponse.
type ListPaymentsResponse struct {
	NextPageToken *string   `json:"next_page_token,omitempty"`
	Payments      []Payment `json:"payments"`
}

// Payment defines model for Payment.
type Payment struct {
	CreateTime time.Time     `json:"create_time"`
	Id         int64         `json:"id"`
	Remark     *string       `json:"remark,omitempty"`
	RequestId  uuid.UUID     `json:"request_id"`
	Reviews    []Review      `json:"reviews"`
	Status     PaymentStatus `json:"status"`
	UpdateTime time.Time     `json:"update_time"`
}

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// Review defines model for Review.
type Review struct {
	Comment    *string     `json:"comment,omitempty"`
	CreateTime time.Time   `json:"create_time"`
	Event      ReviewEvent `json:"event"`
	Id         int64       `json:"id"`
	ReviewerId string      `json:"reviewer_id"`
	UpdateTime time.Time   `json:"update_time"`
}

// ReviewEvent defines model for ReviewEvent.
type ReviewEvent string

// ListPaymentsParams defines parameters for ListPayments.
type ListPaymentsParams struct {
	// Statuses The list of statuses for filtering. if not specified, it will include all statuses.
	Statuses *[]PaymentStatus `form:"statuses,omitempty" json:"statuses,omitempty"`

	// BeforeCreateTimestamp Query the payments before the create timestamp. if not specified, it will use current timestamp
	BeforeCreateTimestamp *int64 `form:"before_create_timestamp,omitempty" json:"before_create_timestamp,omitempty"`

	// PageToken Request a specific page for a list of payments
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// PageSize Specify the maximum number of payments for a page
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody = CreatePaymentRequest

// CreatePaymentReviewJSONRequestBody defines body for CreatePaymentReview for application/json ContentType.
type CreatePaymentReviewJSONRequestBody = CreateReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List payments
	// (GET /payments)
	ListPayments(w http.ResponseWriter, r *http.Request, params ListPaymentsParams)
	// Create payment
	// (POST /payments)
	CreatePayment(w http.ResponseWriter, r *http.Request)
	// Get payment by id
	// (GET /payments/{paymentID})
	GetPaymentByID(w http.ResponseWriter, r *http.Request, paymentID int64)
	// Create review for payment
	// (POST /payments/{paymentID}/reviews)
	CreatePaymentReview(w http.ResponseWriter, r *http.Request, paymentID int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPayments operation middleware
func (siw *ServerInterfaceWrapper) ListPayments(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPaymentsParams

	// ------------- Optional query parameter "statuses" -------------

	err = runtime.BindQueryParameter("form", true, false, "statuses", r.URL.Query(), &params.Statuses)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "statuses", Err: err})
		return
	}

	// ------------- Optional query parameter "before_create_timestamp" -------------

	err = runtime.BindQueryParameter("form", true, false, "before_create_timestamp", r.URL.Query(), &params.BeforeCreateTimestamp)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before_create_timestamp", Err: err})
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_token", r.URL.Query(), &params.PageToken)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", r.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPayments(w, r, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreatePayment operation middleware
func (siw *ServerInterfaceWrapper) CreatePayment(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayment(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPaymentByID operation middleware
func (siw *ServerInterfaceWrapper) GetPaymentByID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "paymentID" -------------
	var paymentID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "paymentID", runtime.ParamLocationPath, chi.URLParam(r, "paymentID"), &paymentID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paymentID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPaymentByID(w, r, paymentID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreatePaymentReview operation middleware
func (siw *ServerInterfaceWrapper) CreatePaymentReview(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "paymentID" -------------
	var paymentID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "paymentID", runtime.ParamLocationPath, chi.URLParam(r, "paymentID"), &paymentID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paymentID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePaymentReview(w, r, paymentID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payments", wrapper.ListPayments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payments", wrapper.CreatePayment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/payments/{paymentID}", wrapper.GetPaymentByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payments/{paymentID}/reviews", wrapper.CreatePaymentReview)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYW2/bNhT+KwS3R8Vyt2wo9NY2XuGhyLKk2UsRBLR0ZLMVLyGP3HiB/vtAirrZihMX",
	"aZqHvcnSIc/l+87HQ9/RVAmtJEi0NLmjNl2BYP7xnQGGcMY2AiSew00JFt17bZQGgxy8lak/XPPM/cqV",
	"EQxpQsuSZzSiuNFAE2rRcLmkEb09Wqqj8NKZTC4v5yf990dcaGW8H8kEdDtphiua0CXHVbmYpErES6WW",
	"BcT+e1VVrTO1+Awp0ioKGZzDmsPXexNIlXAJusdhtFVEYR2+/Gwgpwn9Ke6qFYdSxfX+M29aRdT4n2BC",
	"Rbb29AY3JTeQ0eRTcDBcdDWSycwYZc7BaiUtjOWQQc8ZlwhLMG6hAGvZEh6OxG/R2Y8F8YFbDHSw98ci",
	"4RavNVvCNaovIEfrqsMu7iNHEPahGge3tEOZGcM2O1m0G4/F32yyWz7Pk2vkAgYkzhjCkX8b7eawRXgu",
	"8ffjzq4HgQHBzJfROryU5mkI+HhAatLv4hFRiwzLxwJ6URtXES11digGW9j7THsVbUPpsosGUA+d7mHM",
	"RZsSyFI4X2ez05P56Xsa0TdnZ+d//TNzOJzP/py9+zg76W3VQR0KdpD8fBMvv0WzDuDyPnF7MhTHZPFQ",
	"7Pop9pALeLVwjYDlQuIyV25ZBjY1XCNXkib0ggtdAGFaG7VmBbEbiyBIrgwJyuPy41i47d40Vhdg1jx1",
	"Ma/B2Hqn6eTVZOrCVBok05wm9NfJdDINzeqpEfdlcgk+DUcd5qKZZzQZKLJfaZgABGNp8mk79o8rIAW3",
	"SFRO6sYA6yPPeYHgMp8QnhOpkFgNKc85ZBHhSL7yoiBcpkWZAWFF0a6eOKRudeEPHzQluLLRhN6UYDY0",
	"ajSoMXcN6el3qOp3IrGt/ds5/u08E1xBA4clC8iVAf+u5g9xjLHIhN6Xb2mBpKUxILFbQMcTrF1c9+jZ",
	"WHf5Pthbu8mEiYWwJr6UuGPVY8ZaKHUH/1hsvYO4H85OD+4w3busaynYLRelILIUCzB9pyEW52Sff8v/",
	"hYH7DHJWFkiT36YjlbhyjV+PF54iv0yntVJKDM3MtC546vsg/myV7CbXhyg1OsP4jh/m/2G7vFVEj58w",
	"juFANxLAXK5ZwTPCpS69nrU1e64ILiXcakgRMgLO1ku1LYVgZtNUqF8ereyIRA1uEd0B/VZlmydLZfSm",
	"MpJRbdcETUIotH8AORmrviP/2kH2vugy0pt1/2dcn3FD+PzH9oiM78LT/KS697h8D03vv934yXnvgTk/",
	"6QlAI29+ku6pW/C5w6HDtP/qxzDurG2EBhNHuePnA/xUIflDlTJ7iXR7D62+kcWGhIvSKOPi3vXpETIY",
	"7gIvjH/fS5eH/7/cL8t1DQ9Q5ePdAb32RVCRRTPvZT9eSJ+1p5qmdoNt/lJ7awh5//7k97Jg1k1TlKag",
	"CV0h6iSOC5WyYqUsJq+nr1/R6qr6LwAA//+WjMwTwRQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
