// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Payment is the predicate function for payment builders.
type Payment func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)
